import type { Metadata } from "next";
import "../../globals.css";
import Sidebar from "@/components/common/dashboard/Sidebar";

export const metadata: Metadata = {
  title: "Instituto Pro Vidas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="corporate" lang="en">
      <body className={`antialiased`}>
        <main className="flex">
        <Sidebar />
            {children}</main>
      </body>
    </html>
  );
}
